// Generated by AI (UnitTest MCP)
import { render, screen, fireEvent } from '@testing-library/react';
import { describe, it, expect, vi } from 'vitest';
import { StreamConfig } from '../StreamConfig';

const autocomplete = {
  namespaces: ['default'],
  options: [
    { pod: 'web-1', containers: ['main', 'sidecar'] },
    { pod: 'api-1', containers: ['api'] },
  ],
};

const baseConfig = {
  namespace: 'default',
  query: '.',
  container: '',
};

describe('StreamConfig', () => {
  it('clears container and resets query when the selection is emptied', () => {
    const onChange = vi.fn();
    render(
      <StreamConfig
        config={{ ...baseConfig, container: 'web-1/main' }}
        onChange={onChange}
        autocomplete={autocomplete}
        streamId="1"
      />
    );

    fireEvent.click(screen.getByLabelText('Remove web-1/main'));

    expect(onChange).toHaveBeenCalledWith({ ...baseConfig, container: '', query: '.' });
  });

  it('stores multiple selected containers as a comma-separated container value', () => {
    const onChange = vi.fn();
    render(
      <StreamConfig config={baseConfig} onChange={onChange} autocomplete={autocomplete} streamId="1" />
    );

    fireEvent.click(screen.getByRole('combobox'));
    fireEvent.click(screen.getByLabelText('Select all containers of web-1'));

    expect(onChange).toHaveBeenCalledWith({
      ...baseConfig,
      container: 'web-1/main,web-1/sidecar',
      query: '.',
    });
  });

  it('stores a single container selection in the container field', () => {
    const onChange = vi.fn();
    render(
      <StreamConfig config={baseConfig} onChange={onChange} autocomplete={autocomplete} streamId="1" />
    );

    fireEvent.click(screen.getByRole('combobox'));
    fireEvent.click(screen.getByText('api-1'));
    fireEvent.mouseDown(screen.getByText('api'));

    expect(onChange).toHaveBeenCalledWith({
      ...baseConfig,
      container: 'api-1/api',
      query: '.',
    });
  });
});
