// Generated by AI (UnitTest MCP)
import { render, screen, fireEvent } from '@testing-library/react';
import { describe, it, expect, vi } from 'vitest';
import { LogViewer } from '../LogViewer';

const sampleLogs = [
  { pod: 'web-1', level: 'info', message: 'Server started on port 8080' },
  { pod: 'web-1', level: 'error', message: 'Connection refused to database' },
  { pod: 'api-1', level: 'warn', message: 'Slow query detected' }
];

describe('LogViewer', () => {
  it('renders the empty state when there are no logs', () => {
    render(<LogViewer logs={[]} />);
    expect(screen.getByText('No logs to display yet.')).toBeInTheDocument();
  });

  it('renders log messages', () => {
    render(<LogViewer logs={sampleLogs} />);
    expect(screen.getByText('Server started on port 8080')).toBeInTheDocument();
    expect(screen.getByText('Connection refused to database')).toBeInTheDocument();
    expect(screen.getByText('Slow query detected')).toBeInTheDocument();
  });

  it('renders pod names in brackets', () => {
    render(<LogViewer logs={sampleLogs} />);
    expect(screen.getAllByText('[web-1]')).toHaveLength(2);
    expect(screen.getByText('[api-1]')).toBeInTheDocument();
  });

  it('renders level badges in uppercase', () => {
    render(<LogViewer logs={sampleLogs} />);
    expect(screen.getByText('INFO')).toBeInTheDocument();
    expect(screen.getByText('ERROR')).toBeInTheDocument();
    expect(screen.getByText('WARN')).toBeInTheDocument();
  });

  it('applies wrapping classes to log rows', () => {
    const { container } = render(<LogViewer logs={sampleLogs} />);
    const row = container.querySelector('.whitespace-pre-wrap');
    expect(row).not.toBeNull();
    expect(row.className).toContain('break-words');
  });

  it('renders jump to top and jump to bottom buttons', () => {
    render(<LogViewer logs={sampleLogs} />);
    expect(screen.getByRole('button', { name: /jump to top/i })).toBeInTheDocument();
    expect(screen.getByRole('button', { name: /jump to bottom/i })).toBeInTheDocument();
  });

  it('scrolls to bottom when jump to bottom is clicked', () => {
    const { container } = render(<LogViewer logs={sampleLogs} />);
    const scrollContainer = container.querySelector('.overflow-y-auto');
    const scrollTo = vi.fn();
    scrollContainer.scrollTo = scrollTo;

    fireEvent.click(screen.getByRole('button', { name: /jump to bottom/i }));

    expect(scrollTo).toHaveBeenCalledWith({ top: scrollContainer.scrollHeight, behavior: 'smooth' });
  });

  it('scrolls to top when jump to top is clicked', () => {
    const { container } = render(<LogViewer logs={sampleLogs} />);
    const scrollContainer = container.querySelector('.overflow-y-auto');
    const scrollTo = vi.fn();
    scrollContainer.scrollTo = scrollTo;

    fireEvent.click(screen.getByRole('button', { name: /jump to top/i }));

    expect(scrollTo).toHaveBeenCalledWith({ top: 0, behavior: 'smooth' });
  });

  it('renders fallback text when only text is provided', () => {
    const logs = [{ pod: 'db-1', text: 'raw log line without message' }];
    render(<LogViewer logs={logs} />);
    expect(screen.getByText('raw log line without message')).toBeInTheDocument();
  });
});
