// Generated by AI (UnitTest MCP)
import { render, screen, fireEvent } from '@testing-library/react';
import { describe, it, expect, vi } from 'vitest';
import { LogViewer } from '../LogViewer';

const sampleLogs = [
  { pod: 'web-1', level: 'info', message: 'Server started on port 8080' },
  { pod: 'web-1', level: 'error', message: 'Connection refused to database' },
  { pod: 'api-1', level: 'warn', message: 'Slow query detected' }
];

describe('LogViewer', () => {
  it('renders the empty state when there are no logs', () => {
    render(<LogViewer logs={[]} />);
    expect(screen.getByText('No logs to display yet.')).toBeInTheDocument();
  });

  it('renders log messages', () => {
    render(<LogViewer logs={sampleLogs} />);
    expect(screen.getByText('Server started on port 8080')).toBeInTheDocument();
    expect(screen.getByText('Connection refused to database')).toBeInTheDocument();
    expect(screen.getByText('Slow query detected')).toBeInTheDocument();
  });

  it('renders pod names in brackets', () => {
    render(<LogViewer logs={sampleLogs} />);
    expect(screen.getAllByText('[web-1]')).toHaveLength(2);
    expect(screen.getByText('[api-1]')).toBeInTheDocument();
  });

  it('renders level badges in uppercase', () => {
    render(<LogViewer logs={sampleLogs} />);
    expect(screen.getByText('INFO')).toBeInTheDocument();
    expect(screen.getByText('ERROR')).toBeInTheDocument();
    expect(screen.getByText('WARN')).toBeInTheDocument();
  });

  it('applies wrapping classes to log rows', () => {
    const { container } = render(<LogViewer logs={sampleLogs} />);
    const row = container.querySelector('.whitespace-pre-wrap');
    expect(row).not.toBeNull();
    expect(row.className).toContain('break-words');
  });

  it('renders jump to top and jump to bottom buttons', () => {
    render(<LogViewer logs={sampleLogs} />);
    expect(screen.getByRole('button', { name: /jump to top/i })).toBeInTheDocument();
    expect(screen.getByRole('button', { name: /jump to bottom/i })).toBeInTheDocument();
  });

  it('scrolls to bottom when jump to bottom is clicked', () => {
    const { container } = render(<LogViewer logs={sampleLogs} />);
    const scrollContainer = container.querySelector('.overflow-y-auto');
    const scrollTo = vi.fn();
    scrollContainer.scrollTo = scrollTo;

    fireEvent.click(screen.getByRole('button', { name: /jump to bottom/i }));

    expect(scrollTo).toHaveBeenCalledWith({ top: scrollContainer.scrollHeight, behavior: 'smooth' });
  });

  it('scrolls to top when jump to top is clicked', () => {
    const { container } = render(<LogViewer logs={sampleLogs} />);
    const scrollContainer = container.querySelector('.overflow-y-auto');
    const scrollTo = vi.fn();
    scrollContainer.scrollTo = scrollTo;

    fireEvent.click(screen.getByRole('button', { name: /jump to top/i }));

    expect(scrollTo).toHaveBeenCalledWith({ top: 0, behavior: 'smooth' });
  });

  it('renders fallback text when only text is provided', () => {
    const logs = [{ pod: 'db-1', text: 'raw log line without message' }];
    render(<LogViewer logs={logs} />);
    expect(screen.getByText('raw log line without message')).toBeInTheDocument();
  });

  it('accounts for measured row heights in the scroll geometry', () => {
    const logs = Array.from({ length: 30 }, (_, i) => ({
      id: i,
      pod: 'web-1',
      level: 'info',
      message: `line ${i}`
    }));

    // jsdom reports no layout, so give rows a default height and simulate one
    // wrapped row being taller than ROW_HEIGHT.
    const proto = HTMLElement.prototype;
    const original = Object.getOwnPropertyDescriptor(proto, 'offsetHeight');
    Object.defineProperty(proto, 'offsetHeight', {
      configurable: true,
      get() { return 20; }
    });

    try {
      const { container, rerender } = render(<LogViewer logs={logs} />);
      const rows = container.querySelectorAll('.whitespace-pre-wrap');
      Object.defineProperty(rows[0], 'offsetHeight', { value: 60, configurable: true });

      rerender(<LogViewer logs={logs} />);

      const spacers = container.querySelectorAll('[aria-hidden="true"]');
      const topSpacer = parseFloat(spacers[0].style.height);
      const bottomSpacer = parseFloat(spacers[1].style.height);
      const renderedRows = container.querySelectorAll('.whitespace-pre-wrap');
      const renderedHeight = Array.from(renderedRows).reduce(
        (sum, row) => sum + row.offsetHeight,
        0
      );

      // 29 rows at 20px + 1 wrapped row at 60px = 640px total scroll height.
      expect(topSpacer + renderedHeight + bottomSpacer).toBe(640);
    } finally {
      if (original) Object.defineProperty(proto, 'offsetHeight', original);
      else delete proto.offsetHeight;
    }
  });

  it('renders rows taller than the viewport budget instead of blanking the window', () => {
    const logs = Array.from({ length: 30 }, (_, i) => ({
      id: i,
      pod: 'web-1',
      message: `line ${i}`
    }));

    // jsdom reports no layout, so give rows a default height and simulate one
    // hugely wrapped row (taller than viewport + overscan budget, which is
    // 240px in jsdom where clientHeight is 0).
    const proto = HTMLElement.prototype;
    const original = Object.getOwnPropertyDescriptor(proto, 'offsetHeight');
    Object.defineProperty(proto, 'offsetHeight', {
      configurable: true,
      get() { return 20; }
    });

    try {
      const { container, rerender } = render(<LogViewer logs={logs} />);
      const rows = container.querySelectorAll('.whitespace-pre-wrap');
      Object.defineProperty(rows[5], 'offsetHeight', { value: 2000, configurable: true });

      rerender(<LogViewer logs={logs} />);

      // The tall row must still be rendered once its top edge scrolls into
      // the budget — the window must never end up with zero rows.
      const rendered = container.querySelectorAll('.whitespace-pre-wrap');
      expect(rendered.length).toBeGreaterThan(0);
      expect(Array.from(rendered).some((r) => r.textContent.includes('line 5'))).toBe(true);

      // Simulate scrolling to the tall row and verify it stays rendered.
      const scrollContainer = container.querySelector('.overflow-y-auto');
      Object.defineProperty(scrollContainer, 'scrollTop', { value: 110, configurable: true });
      fireEvent.scroll(scrollContainer);

      const afterScroll = container.querySelectorAll('.whitespace-pre-wrap');
      expect(afterScroll.length).toBeGreaterThan(0);
      expect(Array.from(afterScroll).some((r) => r.textContent.includes('line 5'))).toBe(true);
    } finally {
      if (original) Object.defineProperty(proto, 'offsetHeight', original);
      else delete proto.offsetHeight;
    }
  });
});
